import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Open_Sans } from 'next/font/google';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'my-log',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <header className='flex justify-between items-center mx-4 h-16'>
          <h1 className='text-4xl'>my-log</h1>
          <nav className='flex gap-4 text-xl'>
            <Link href='/'>HOME</Link>
            <Link href='/'>ABOUT</Link>
            <Link href='/'>POST</Link>
            <Link href='/'>CONTACT</Link>
          </nav>
        </header>
        {children}
      </body>
      <footer>
        od made
      </footer>
    </html>
  )
}
